pool:
  vmImage: 'ubuntu-latest'
trigger:
  - master
steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'deployment'
      Contents: '*.json'
      TargetFolder: '$(build.artificactstagingdirectory)/Templates'
  - task: Npm@1
    displayName: 'npm custom'
    inputs:
      command: 'custom'
      verbose: false
      customCommand: 'install --production'
  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.SourceDirectory)'
    inputs:
      rootFolderOrFile: '$(Build.SourceDirectory)'
      includeRootFolder: false
  - task: CopyPublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'